spring.datasource.url=jdbc:postgresql://localhost:5432/im_portal_db
spring.datasource.username=postgres
spring.datasource.password=D1n2thy3@UoK

spring.jpa.hibernate.ddl-auto = update
spring.jpa.show-sql = true
spring.jpa.properties.hibernate.dialect = org.hibernate.dialect.PostgreSQLDialect

spring.servlet.multipart.max-file-size=10MB
spring.servlet.multipart.max-request-size=10MB

cloudinary.cloud_name=dehua8dd5
cloudinary.api_key=716717687623782
cloudinary.api_secret=9ow4ICANa6uK_oRNL4UfTnWo-eo

spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=gymdinethya@gmail.com
spring.mail.password=sxow hges npof jlqm

#spring.mail.protocol=smtp
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true

#spring.mail.host=smtp.gmail.com
#spring.mail.port=587
#spring.mail.username=gymdinethya@gmail.com
#spring.mail.password=wooo khev mjts ikfz
#
#spring.mail.protocol=smtp
#spring.mail.properties.mail.smtp.auth=true
#spring.mail.properties.mail.smtp.starttls.enable=true
#spring.mail.properties.mail.smtp.starttls.required=true
#
#spring.mail.properties.mail.smtp.ssl.trust=*
#spring.mail.properties.mail.smtp.ssl.protocols=TLSv1.2
#spring.mail.properties.mail.smtp.connectiontimeout=10000
#spring.mail.properties.mail.smtp.timeout=10000
#spring.mail.properties.mail.smtp.writetimeout=10000
